# Generated by Django 3.0.1 on 2023-03-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, null=True)),
                ('apellido', models.CharField(max_length=40, null=True)),
                ('distancia', models.CharField(choices=[('', 'Seleccione una distancia'), ('1', '5K TREKKING'), ('2', '5K COMPETITIVO'), ('3', '10K COMPETITIVO'), ('4', '21K COMPETITIVO')], default='', max_length=2, null=True)),
                ('archivo', models.FileField(upload_to='infpago/infpago/media/documentos')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
