# Generated by Django 3.0.1 on 2023-03-07 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pago', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descuentos', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Codigos',
        ),
    ]
