# Generated by Django 3.0.1 on 2023-03-07 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pago', '0003_auto_20230307_2050'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cupon',
        ),
    ]
