# Generated by Django 3.0.1 on 2023-04-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pago', '0005_cupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupon',
            name='porcentaje_descuento',
            field=models.IntegerField(null=True),
        ),
    ]
