# Generated by Django 4.1.2 on 2023-02-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='categoria',
            field=models.CharField(choices=[(1, 'uno'), (2, 'dos')], max_length=40, null=True),
        ),
    ]
