# Generated by Django 3.0.1 on 2023-03-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0002_alter_usuario_categoria_alter_usuario_genero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='distancia',
            field=models.CharField(choices=[('', 'Seleccione una distancia'), ('1', '5K TREKKING'), ('2', '5K COMPETITIVO'), ('3', '10K COMPETITIVO'), ('4', '21K COMPETITIVO')], default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
