# Generated by Django 3.0.1 on 2023-03-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0003_auto_20230311_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='talle_de_remera',
            field=models.CharField(choices=[('', 'Seleccione un talle de remera'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='', max_length=40, null=True),
        ),
    ]
