# Generated by Django 4.1.2 on 2023-02-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0003_alter_usuario_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='categoria',
            field=models.CharField(choices=[(0, 'Seleccione una categoria'), (1, 'Edad: 15-20 años'), (2, 'Edad: 20-25 años'), (3, 'Edad: 25-30 años'), (4, 'Edad: 30-35 años'), (5, 'Edad: 35-40 años'), (6, 'Edad: 40-45 años'), (7, 'Edad: 45-50 años'), (8, 'Edad: 50-55 años'), (9, 'Edad: 55-60 años'), (10, 'Edad: 60-65 años'), (11, 'Edad: +70 años')], default=0, max_length=40, null=True),
        ),
    ]
