# Generated by Django 4.1.2 on 2023-02-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0004_alter_usuario_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='talle_de_remera',
            field=models.CharField(choices=[(0, 'Seleccione un talle de remera'), (1, 'XS'), (2, 'S'), (3, 'M'), (4, 'L'), (5, 'XL')], default=0, max_length=40, null=True),
        ),
    ]
