# Generated by Django 3.0.1 on 2023-04-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0005_usuario_compro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='categoria',
            field=models.CharField(choices=[('', 'Seleccione una categoria'), ('15-19', 'Edad: 15-19 años'), ('20-24', 'Edad: 20-24 años'), ('25-29', 'Edad: 25-29 años'), ('30-34', 'Edad: 30-34 años'), ('35-39', 'Edad: 35-39 años'), ('40-44', 'Edad: 40-44 años'), ('40-44', 'Edad: 45-49 años'), ('50-54', 'Edad: 50-54 años'), ('55-59', 'Edad: 55-59 años'), ('60-64', 'Edad: 60-64 años'), ('160-64', 'Edad: c años'), ('70', 'Edad: +70 años')], default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='distancia',
            field=models.CharField(choices=[('', 'Seleccione una distancia'), ('5', '5K TREKKING'), ('5k', '5K COMPETITIVO'), ('10', '10K COMPETITIVO'), ('21k', '21K COMPETITIVO')], default='', max_length=40, null=True),
        ),
    ]
