# Generated by Django 4.1.2 on 2023-02-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0005_alter_usuario_talle_de_remera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.CharField(choices=[(0, 'Seleccione su genero'), (1, 'Masculino'), (2, 'Femenino'), (3, 'Otros')], default=0, max_length=40, null=True),
        ),
    ]
